### ISSUE TITLE
Do you complete mqtt protocol on server side?

### ISSUE THREAD

**Issue by xudeheng** [vbotnaru/mqtt#1]

**Comment by vbotnaru** [comment]
what do you mean by "complete"?  i'm using mqtt nodejs module to connect to the broker and subscribe to topic. after you can receive messages from broker and  forward them to client using sockets or to store data in db.

**Comment by xudeheng** [comment]
I'v supposed you complete mqtt server site protocol in nodejs. : )

**Comment by vbotnaru** [comment]
https://www.npmjs.com/package/mqtt

**Comment by xudeheng** [comment]
Thanks. It's useful for me.
